### ISSUE TITLE
memorable option should not disable pattern

### ISSUE THREAD

**Issue by onury** [bermi/password-generator#14]
if memorable is enabled, you cannot get a password that matches the pattern. Always generates lower-cased letters.

```js
generatePassword(10, true, /\d/);           // —> cuyupizuvo  (no numbers)
generatePassword(10, true, /[a-zA-Z]/);     // —> felunaturo  (could be FeluNAturo)
generatePassword(10, true, /[a-zA-Z\d]/);   // —> cimatugije  (could be C1matu9ije)
```

**Comment by bermi** [comment]
Memorable passwords right now are always consonant vowel pairs. Matching a password against regex and keep it readable seems like a difficult task. Suggestions or PR's on how to achieve it are welcomed.

**Comment by onury** [comment]
Well, I've implemented a simple logic over the generated result. regex-match is problematic for this feature, so I had to create a different API for my use case. Thanks anyway.
