### ISSUE TITLE
Doesn't work in old versions of IE as claimed

### ISSUE THREAD

**Issue by edg2s** [bermi/password-generator#16]
Typed arrays (UInt8Array) was only added in IE10 (http://caniuse.com/#feat=typedarrays)

![screenshot from 2016-12-04 15-41-21](https://cloud.githubusercontent.com/assets/180672/20867285/5b050858-ba38-11e6-8722-546d572e6a7a.png)

**Comment by bermi** [comment]
We'll have to upgrade the docs and remove the test result badge since it's no longer working.

Since v2.0.0 support for IE starts on IE11. We moved from Math.random to crypto.getRandomValues  http://caniuse.com/#feat=getrandomvalues (bermi/password-generator#11)
