### ISSUE TITLE
algorithm behind

### ISSUE THREAD

**Issue by robert197** [bermi/password-generator#19]
i would like to know if there is a known algorithm behind this password generation library. if there is one, which one? 
thank you

**Comment by bermi** [comment]
@robert197 https://github.com/bermi/password-generator/blob/master/lib/password-generator.js#L93 uses https://developer.mozilla.org/en/docs/Web/API/RandomSource/getRandomValues when running on browsers or http://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_randombytes_size_callback when running on node.js which uses https://www.openssl.org/docs/man1.0.2/crypto/RAND_bytes.html under the hood.
