### ISSUE TITLE
Request: Add support for random seed

### ISSUE THREAD

**Issue by Kyrrui** [bermi/password-generator#23]
I want to create username's that conform to UTF-8 (chars only) based on emails. If I could plug in a seed for the random password generator then I could use your library to generate usernames based on email addresses.

**Comment by bermi** [comment]
My understanding is that `crypto.getRandomValues` uses an automatic seed that's meant to be secure.

Right now only chars between 33 and 126 are taken into consideration for passwords, allowing UTF-8 would require a different and potentially slower algorithm. 

I'm open to PR's if someone has a clever way to support it without affecting the performance. In the mean time we should keep the scope of this library as small as possible
