### ISSUE TITLE
Uniqueness

### ISSUE THREAD

**Issue by lastmjs** [bermi/password-generator#24]
How likely are generated passwords to be unique? Is there any mechanism in the algorithm used that can ensure uniqueness with high probability?

**Comment by bermi** [comment]
@lastmjs the algorithm uses a secure random number generator https://github.com/bermi/password-generator/blob/master/lib/password-generator.js#L93. That said if you use the `memorable` pass option or a custom password pattern, chances of hitting a duplicated password increase.

**Comment by lastmjs** [comment]
Great, thank you
