### ISSUE TITLE
Unable to generate a password with the tilde character

### ISSUE THREAD

**Issue by fshields** [bermi/password-generator#26]
It is not possible to generate a password with a tilde (~) character in it.  We get an error when this is executed:
`generatePassword(12, false, /[\~]/)`

The error lies in the loop bounds on [Line 39 of /dist/password-generator.js](https://github.com/bermi/password-generator/blob/master/dist/password-generator.js#L39):
    `for (i = 33; 126 > i; i += 1) {`
The variable `i` will never reach ASCII 126 (the tilde character)

That line should be updated to:
    `for (i = 33; 126 >= i; i += 1) {`
or the more normal representation:
    `for (i = 33; i <= 126; i += 1) {`

(I saw that you just fixed issue #25 and released v2.2.2.  Thank you!  I wish I had caught this sooner so that it could have been rolled into that release.)

**Comment by bermi** [comment]
Thanks @fshields, just pushed the fix as 2.2.3
