### ISSUE TITLE
How to make sure password contains both letters and characters 

### ISSUE THREAD

**Issue by dibeesh** [bermi/password-generator#4]
Hi,
Am using following method to generate random password 
var pwd = generatePassword(8, false)
but sometimes its generating letters only passwords. How to make sure my password must contains both letters and digits. 
Thank you.

**Comment by bermi** [comment]
You could probably combine a 7 letter password with a random number or use ca custom regexp such as:

    generatePassword(8, false, /[\w\d]{3,6}[\d][\w\d]+/)

**Comment by mleanos** [comment]
@bermi The pattern you supplied above isn't being accepted by generatePassword

I get an error that states: 
```
[Error: Could not find characters that match the password pattern /[\w\d]{3,6}[\d][\w\d]+/. Patterns must match individual characters, not the password as a whole.]
```
https://github.com/bermi/password-generator/issues/10

**Comment by bermi** [comment]
That's true @mleanos I've added an example on #10 that could be edited to validate a composed password. I will probably update the readme file in order to include it.
