### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by netsi1964** [bermi/password-generator#6]
When calling the method like this:
`generatePassword(11, false, /test/)`
in the browser you will receive this error:
`Uncaught RangeError: Maximum call stack size exceeded`

**Comment by bermi** [comment]
/test/ will never match a single character. Updated the code to throw an exception on this case. Also improved the performance for short matches like /(t|e|s|t)/.

Released as 1.0.0 on npm
